#ifndef __TECMA_ENUMS_H 
#define __TECMA_ENUMS_H

enum TecmaStatus {          // basic stuff to know what the engine is doing
    TECMA_STATUS_IDLE = -1,
    TECMA_STATUS_INIT_ENGINE = 0,
    TECMA_STATUS_CREATING_NEW_THREAD = 1,
    TECMA_STATUS_INIT_WINDOW = 2,
    TECMA_STATUS_INIT_VULKAN = 3,

};

enum TecmaButtonFunctionalityType {
    TECMA_BUTTON_FUNCTION_CLOSE = 0,
    TECMA_BUTTON_FUNCTION_EXPAND = 1,
    TECMA_BUTTON_FUNCTION_MINIMALIZE = 2,
    TECMA_BUTTON_FUNCTION_CUSTOM = 3,

};

enum TecmaResult {
    TECMA_RESULT_SUCCESS = 0,
    TECMA_RESULT_X_OPEN_DISPLAY_FAILED = 1,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_VALUE = 2,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_WINDOW = 3,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_PIXMAP = 4,
    TECMA_RESULT_X_FAILED_TO_MATCH_VISUAL_INFO = 5,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_CURSOR = 6,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_MATCH = 8,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_ALLOC = 11,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_COLOR = 12,
    TECMA_RESULT_TE_UNKNOWN_STATUS_TYPE = 7, 
};

#endif