#ifndef __TECMA_ENUMS_H 
#define __TECMA_ENUMS_H

enum TecmaResult {
    TECMA_RESULT_SUCCESS = 0,
    TECMA_RESULT_X_OPEN_DISPLAY_FAILED = 1,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_VALUE = 2,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_WINDOW = 3,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_PIXMAP = 4,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_CURSOR = 6,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_MATCH = 8,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_ALLOC = 11,
    TECMA_RESULT_X_CREATE_WINDOW_BAD_COLOR = 12,
};

#endif